### ISSUE TITLE
"Could not load new packages"

### ISSUE THREAD

**Issue by mitchmindtree** [vlinkz/nix-software-center#1]
Hey great to see something like this started, the app looks beautiful from the screenshots!

I had a go at running it, but to no luck:

![Screenshot from 2022-09-09 13-50-38](https://user-images.githubusercontent.com/4587373/189268643-16a444af-b913-4cfe-88bd-ef680a243488.png)

Some notes:
- I am on the internet (that's how I could `nix run` it).
- I don't have a `configuration.nix` in the `/etc/nixos` location. I keep my main configuration in a flake under a directory within my `$HOME` (not sure if this affects the package search).
- System details:
  ```
  [mindtree@minddesk:~]$ nix run nixpkgs#nix-info -- -m
  - system: `"x86_64-linux"`
  - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11.20220813.e105167`
  - multi-user?: `yes`
  - sandbox: `yes`
  - version: `nix-env (Nix) 2.10.3`
  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
  ```

**Comment by tejing1** [comment]
Same issue, my system config is also a flake, and not at `/etc/nixos`, though `nixos-rebuild` finds it properly through the symlink I placed at `/etc/nixos/flake.nix`. It might also be relevant here that I don't have any channels, instead handling `NIX_PATH` through my config flake setup. (so `<nixpkgs>` does resolve on my system, just not through channels)

**Comment by mitchmindtree** [comment]
> It might also be relevant here that I don't have any channels, instead handling NIX_PATH through my config flake setup.

Likewise, fwiw.

**Comment by marsupialgutz** [comment]
Same issue here, I have my nixos configuration as a flake in my home directory.

**Comment by vlinkz** [comment]
Just pushed some changes with a new welcome screen that allows you to choose your config locations. It should be able to detect that you don't have your configs in the default location and prompt you next time your run the application. Hopefully, it works for all of you, and thanks for the report! (Also I'll make a new tag release soon after fixing some other bugs)
![Screenshot from 2022-09-12 18-09-23](https://user-images.githubusercontent.com/20145996/189767729-a50d948b-8902-4276-8aff-2b49ddcdbd16.png)

**Comment by tejing1** [comment]
Tried the new version, but even when I manually point it at my flake.nix and one of the modules in my config (I have it split up into multiple files), it still fails in exactly the same way. Still thinking the issue has to do with me not using channels.

**Comment by vlinkz** [comment]
@tejing1 Should be fixed in the latest tag release

**Comment by tejing1** [comment]
Afraid not. I tried both master and 0.0.3, and I tried removing `~/.cache/nix-software-center` just in case, but I still get the same error.

**Comment by vlinkz** [comment]
Weird, any output from `RUST_LOG=nix_software_center=trace nix-software-center`? Also maybe try also removing `~/.config/nix-software-center` and setup your `flake.nix` and `configuration.nix` from the welcome screen again

**Comment by tejing1** [comment]
```
$ RUST_LOG=nix_software_center=trace nix run github:vlinkz/nix-software-center/0.0.3
 DEBUG nix_software_center::ui::window > Got config: NscConfig { systemconfig: Some("/mnt/persist/tejing/flake/nixosConfigurations/tejingdesk/tejing.nix"), flake: Some("/mnt/persist/tejing/flake/flake.nix"), flakearg: None }
 DEBUG nix_software_center::ui::window > userpkgtype: Profile
 DEBUG nix_software_center::ui::window > syspkgtype: Flake
 INFO  nix_software_center::ui::windowloading > WindowAsyncHandlerMsg::CheckCache
 INFO  nix_software_center::parse::cache      > Setting up flake cache
 INFO  nix_software_center::parse::cache      > NEW REV: 13cbe534ebe63a0bc2619c57661a2150569d0443
 TRACE nix_software_center::parse::cache      > Downloading https://channels.nixos.org/nixos-22.05/packages.json.br
 TRACE nix_software_center::parse::cache      > Finished downloading https://channels.nixos.org/nixos-22.05/packages.json.br -> /home/tejing/.cache/nix-software-center/packages.json
 INFO  nix_software_center::parse::cache      > Setting up profile package cache
 INFO  nix_software_center::parse::cache      > PROFILE REV c4d0026e7346ad2006c2ba730d5a712c18195aab
 TRACE nix_software_center::parse::cache      > Downloading https://channels.nixos.org/nixpkgs-22.05/packages.json.br
 TRACE nix_software_center::parse::cache      > Finished downloading https://channels.nixos.org/nixpkgs-22.05/packages.json.br -> /home/tejing/.cache/nix-software-center/profilepackages.json
 INFO  nix_software_center::parse::packages   > Reading package list
 TRACE nix_software_center::parse::packages   > Reading packages.json
 WARN  nix_software_center::ui::windowloading > FAILED TO LOAD PKGS
 WARN  nix_software_center::ui::windowloading > Serde("missing field `github`") at character 0 ('💩')
```
I also tried re-selecting the files, nothing different.

**Comment by vlinkz** [comment]
Found an error in cache downloading based on that log. Hopefully, the new master (b1a89ece314d9a9757d764d4038a9e849db5b280) should work 🤞🏽

**Comment by tejing1** [comment]
Nope. Same error, same trace output from b1a89ece314d9a9757d764d4038a9e849db5b280.

**Comment by vlinkz** [comment]
Should now actually be fixed in the latest commit. Seems like the 22.05 `packages.json` has some malformed `maintainers` sections for a few packages, so added a filter that should mitigate the issue

**Comment by tejing1** [comment]
630a718baca2c49f98e5e53b99c348c18752be00 does successfully start for me. :tada:

**Comment by Birdthatcantfly** [comment]
I got an error on the nixos-unstable-small. 
`
ERROR nix_software_center::parse::cache > Failed to download https://releases.nixos.org/nixos/unstable/nixos-22.11pre413099.bd9f4f3ae03/packages.json.br
`
But after switching to nixos-unstable everything works.
